[workspace]
resolver = "2"
members = ["squishy_game", "squishy_lib"]

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
codegen-units = 1
lto = "fat"
strip = "symbols"
