[package]
name = "squishy_game"
version = "0.1.0"
edition = "2024"
license = ""
authors = ["Tadeusz Pawlonka <tadeuszpawlonka@gmail.com>"]

[dependencies]
bevy = "0.15.0"
squishy_lib = {path = "../squishy_lib", version = "*"}